apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: rate
  labels:
    strimzi.io/cluster: prices-cluster
  namespace: prices-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
